env:
  - RELEASE_BUILDS=dist/gotp_darwin_amd64/gotp dist/gotp_linux_amd64/gotp dist/gotp_windows_amd64/gotp.exe dist/gotp_linux_arm_6/gotp dist/gotp_linux_arm64/gotp

before:
  hooks:
    - make deps

builds:
  - binary: gotp
    main: ./cmd/main.go
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm
      - arm64
    ldflags:
      - -s -w -X "main.buildString={{ .Tag }} ({{ .ShortCommit }} {{ .Date }})"

    hooks:
      # stuff executables with static assets.
      post: make pack-releases

archives:
  - format: tar.gz
    files:
      - README.md
      - LICENSE
